# Generated by Django 4.0.6 on 2022-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
